# Generated by Django 6.0.1 on 2026-02-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(default='Inget utdrag ännu'),
            preserve_default=False,
        ),
    ]
